#!/bin/sh
#
# work around a NetworkManager bug, waking it up after resume (sometimes it
# stays sleeping after resume)
#
# sudo cp 49_network-manager /etc/pm/sleep.d/49_network-manager
# sudo chmod 755 /etc/pm/sleep.d/49_network-manager
#

case "$1" in
        resume|thaw)
                service network-manager restart
                ;;
        suspend|hibernate)
                # Do nothing
                ;;
esac
